### ISSUE TITLE
Bitwise & instead of logical &&

### ISSUE THREAD

**Issue by MatthewCallis** [wkallhof/Hazel#16]
There is a missing `&` on this line https://github.com/wkallhof/Hazel/blob/master/app/controllers/documentController.js#L121

Didn't find this until I was too deep into hacking away and changed basically every single file otherwise I would open a PR.

Thanks for making/releasing/sharing this!

**Comment by wkallhof** [comment]
Should be resolved with the latest 1.1.8. Thanks for finding this!
