### ISSUE TITLE
Does not work for nested folders with markdown files

### ISSUE THREAD

**Issue by jrichardsz** [wkallhof/Hazel#25]
I tried to use this tool to my dozens of folders with markdown but only markdown files in root path are scanned.

Also new created documents are stored in root content folder without option to create or locate an  folder.

Is this functionality implemented?

Thanks a lot.

**Comment by wkallhof** [comment]
@jrichardsz Hazel wasn't designed with folder structures in mind. Organization is done through metadata and tagging. As it stands, it only scans the root folder.

**Comment by jrichardsz** [comment]
I made some changes and works with nested folders. Only **create new documents** functionality with folder selection is in progress. 

What kind of guidelines are required to adopt this new functionality to your project?

Thanks
