### ISSUE TITLE
Running behind Apache proxy, `base` directive doesn't seem to have any effect

### ISSUE THREAD

**Issue by gruentee** [wkallhof/Hazel#3]
Hello there, first of all – thanks for your effort, Hazel looks great as far as I can judge from what I've seen so far.

However, trying to set up my personal instance on a shared hosting I encountered the following error.
I'm attempting to run Hazel behind an Apache and in a sub-directory:

http://domain.com/wiki

Therefore I set `base` in my `config.default.js`:

``` js
var config = {
  //  Your site title (format: page_title - site_title)
  site_title: "Abacus Wiki",

  //Application base url
  base: "/wiki/",
};
// Exports
module.exports = config;
```

My `.htaccess` in the specified dir `/wiki` contains a rewrite

``` htaccess
RewriteEngine On
RewriteRule (.*) http://localhost:62626/$1 [P]
```

directing any request to the running Hazel server.

Still the paths in the resulting HTML pages are incorrect (e.g. `/styles/tidy.css`) resulting in un-styled pages.

What is wrong here?

**Comment by wkallhof** [comment]
@gruentee with the latest version I pushed out today (1.1.3), there are corrections for how assets are referenced. Please try the latest version and let me know if you continue to run into issues.

**Comment by gruentee** [comment]
Thanks Wade, works perfectly now.
